### ISSUE TITLE
[Vraagje] Tekst over image

### ISSUE THREAD

**Issue by HiddeStatema** [CMDA/mi-mobile-design-forum#49]
Ik heb de nieuwsopdracht gekozen en wil tekst over een plaatje zetten. Iemand een idee, behalve met margin-top: -100px?

Zat te denken aan pisition absolute, maar dan heb je een probleem met responsive..

**Comment by aproskam** [comment]
Afbeelding als background in de CSS verwerken? Is natuurlijk niet de ideale oplossing

**Comment by vasilisvg** [comment]
@HiddeStatema Ik snap niet helemaal wat je bedoelt met het idee dat position absolute niet zou werken met responsive. `position: absolute; left: 0; right: 0;` werkt gewoon prima. 
Kijk anders ook even naar een van die links die ik van de week postte over captions. Daar staat vast bruikbare code bij.

**Comment by HiddeStatema** [comment]
Vasilis, ik wil zeg maar tekst over een plaatje heen zetten en onderaan uitlijnen. Ik heb niet echt een voorbeeld, dus vandaar <a href="http://www.hiddestatema.com/dit.png">dit</a> prachtige photoshopje.
Zoals ik het nu heb opgelost:
h1 {
margin-top: -100px;
}

Echter als de tekst langer dan 1 regel wordt, staat maar een regel op de afbeelding.. Afbeelding als achtergrond is niet de beste oplossing denk ik. Zat al iets te klooien met line-height, maar nog niks bruikbaars.. Heb het ook nog niet echt ergens gezien waar ik met element inspecteren kan "stelen".

**Comment by vasilisvg** [comment]
Uit mijn hoofd:

``` html
<figure>
    <img src="mooiplaatje.jpg" alt="">
    <figcaption>Dit moet over dat plaatje heen staan</figcaption>
</figure>
```

``` css
figure {
    position: relative;
    display: table;
    width: 1em; 
}
figure img {
    display: block;
}
figcaption {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
}
```

Zie hier het resultaat: http://dabblet.com/gist/7cfed7dd56c842e749be
